// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Inclusive date range. Dates must be in YYYY-MM-DD.
type DateRange struct {
	// Format YYYY-MM-DD.
	StartDate time.Time `json:"startDate"`
	// End date (YYYY-MM-DD).
	EndDate time.Time `json:"endDate"`
}

type FilterHyperquack struct {
	Protocol  string    `json:"protocol"`
	Asn       int       `json:"asn"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type FilterSatellite struct {
	Asn       int       `json:"asn"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type Query struct {
}
