// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Inclusive date range. Dates must be in YYYY-MM-DD.
type DateRange struct {
	// Start date (YYYY-MM-DD).
	StartDate time.Time `json:"startDate"`
	// End date (YYYY-MM-DD).
	EndDate time.Time `json:"endDate"`
}

type FilterDashboard struct {
	Domains   []string  `json:"domains"`
	Country   string    `json:"country"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
	Source    string    `json:"source"`
}

type FilterHyperquack struct {
	Protocol  string    `json:"protocol"`
	Domain    string    `json:"domain"`
	Country   string    `json:"country"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type FilterSatellite struct {
	Domain    string    `json:"domain"`
	Country   string    `json:"country"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type Query struct {
}
