// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Filter struct {
	Protocol  string `json:"protocol"`
	Domain    string `json:"domain"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type Hyperquack struct {
	Protocol        string  `json:"protocol"`
	Domain          string  `json:"domain"`
	DomainIsControl *bool   `json:"domainIsControl,omitempty"`
	Date            string  `json:"date"`
	StartTime       string  `json:"startTime"`
	EndTime         string  `json:"endTime"`
	ServerIP        *string `json:"serverIp,omitempty"`
	ServerNetblock  *string `json:"serverNetblock,omitempty"`
	ServerCountry   string  `json:"server_country"`
}

type Query struct {
}
